apiVersion: v1
kind: Secret
metadata:
  name: fleet-controller-secrets
  namespace: bunker-fleet
type: Opaque
stringData:
  JWT_SECRET: "bunker-fleet-production-jwt-secret-change-me-in-production-2024"
  DATABASE_PASSWORD: "secure-bunker-db-password-2024"
  REDIS_PASSWORD: ""