apiVersion: v1
kind: Service
metadata:
  name: fleet-controller-service
  namespace: bunker-fleet
  labels:
    app: fleet-controller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fleet-controller